kind: pipeline
type: docker
name: netdevops cicd proof of concept

steps:
  - name: starting build
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    commands:
      - echo 'starting build'
      - git --version
      - python --version
      - pip list
      - git fetch
      - git checkout ${DRONE_BRANCH}
  
  - name: dry run
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    environment:
      NORNIR_USER:
        from_secret: NORNIR_USER
      NORNIR_SECRET:
        from_secret: NORNIR_SECRET
    commands:
      - git fetch
      - python deploy_baseconfig.py --dry_run
    when:
      branch:
        - dev
  
  - name: merge to main 
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    environment:
      GITLAB_USER:
        from_secret: GITLAB_USER
      GITLAB_PASS:
        from_secret: GITLAB_PASS
    commands:
      - git checkout main
      - git branch -u origin/main
      - git merge dev
      - git remote -v
      # - git remote rm origin
      # - git remote add origin http://$GITLAB_USER:$GITLAB_PASS@192.168.1.200/${DRONE_REPO}.git
      # - git remote -v ssh://git@192.168.0.200:2222/vireakouk/nornir-scrapli-eos-lab.git
      - git push --all
      - git push --tags
    when:
      branch:
        - dev
        
  - name: deploy to production
    image: vireakouk/netdevops-drone-nornir-scrapli:latest
    environment:
      NORNIR_USER:
        from_secret: NORNIR_USER
      NORNIR_SECRET:
        from_secret: NORNIR_SECRET
    commands:
      - python deploy_baseconfig.py
    when:
      branch:
        - main

  # - name: send telegram notification
  #   image: appleboy/drone-telegram
  #   settings:
  #     token: xxxxxxxxxx
  #     to: telegram_user_id
  #     message: >
  #       {{#success build.status}}
  #         build {{build.number}} succeeded. Good job.
  #       {{else}}
  #         build {{build.number}} failed. Fix me please.
  #       {{/success}}