---
nxos:
  connection_options:
    scrapli:
      platform: cisco_nxos
      extras:
        # ssh_config_file: True
        auth_strict_key: False

eos:
  # port: 6030
  connection_options:
    scrapli:
      platform: arista_eos
      # port: 22
      extras:
        # ssh_config_file: True
        auth_strict_key: False

