---
spine1.eos:
  hostname: 172.100.1.11
  role: spine
  data:
    name: spine1
    loopback_ipv4: 1.1.1.1/32
    loopback_ipv6: 2001:1:1:1::1/128
  groups:
    - eos
spine2.eos:
  hostname: 172.100.1.12
  role: spine
  data:
    name: spine2
    loopback_ipv4: 1.1.1.2/32
    loopback_ipv6: 2001:1:1:1::2/128
  groups:
    - eos
leaf1.eos:
  hostname: 172.100.1.13
  role: leaf
  data:
    name: leaf1
    loopback_ipv4: 1.1.1.3/32
    loopback_ipv6: 2001:1:1:1::3/128
  groups:
    - eos
leaf2.eos:
  hostname: 172.100.1.14
  role: leaf
  data:
    name: leaf2
    loopback_ipv4: 1.1.1.4/32
    loopback_ipv6: 2001:1:1:1::4/128
  groups:
    - eos
...