---
pd01-ilf-021:
  hostname: 10.0.10.134
  data:
    interfaces:
      eth47:
        name: 47
        ipv4: 169.254.34.186
  groups:
    - nxos



pd01-ilf-022:
  hostname: 10.0.10.194
  data:
    interfaces:
      eth47:
        name: 47
        ipv4: 169.254.42.186
  groups:
    - nxos

...