---
spine1.eos:
  hostname: 172.100.1.11
  role: spine
  data:
    name: spine1
    loopback_ipv4: 1.1.1.1/32
    loopback_ipv6: 2001:1:1:1::1/128
    interfaces:
      eth1:
        name: Ethernet1
        desc: "To leaf1"
        ipv4: 10.1.1.0/31
        ipv6: 2010:1:1:2::0/127
      eth2:
        name: Ethernet2
        desc: "To leaf2"
        ipv4: 10.1.1.2/31
        ipv6: 2010:1:1:2::2/127
  groups:
    - eos
    - spine
spine2.eos:
  hostname: 172.100.1.12
  role: spine
  data:
    name: spine2
    loopback_ipv4: 1.1.1.2/32
    loopback_ipv6: 2001:1:1:1::2/128
    interfaces:
      eth1:
        name: Ethernet1
        desc: "To leaf1"
        ipv4: 10.1.1.4/31
        ipv6: 2010:1:1:2::4/127
      eth2:
        name: Ethernet2
        desc: "To leaf2"
        ipv4: 10.1.1.6/31
        ipv6: 2010:1:1:2::6/127
  groups:
    - eos
    - spine
leaf1.eos:
  hostname: 172.100.1.13
  role: leaf
  data:
    name: leaf1
    loopback_ipv4: 1.1.1.3/32
    loopback_ipv6: 2001:1:1:1::3/128
    interfaces:
      eth1:
        name: Ethernet1
        desc: "To spine1"
        ipv4: 10.1.1.1/31
        ipv6: 2010:1:1:2::1/127
      eth2:
        name: Ethernet2
        desc: "To spine2"
        ipv4: 10.1.1.5/31
        ipv6: 2010:1:1:2::5/127
      eth3:
        name: Ethernet3
        desc: "To client1"
        ipv4: 10.1.1.8/31
        ipv6: 2010:1:1:2::8/127
  groups:
    - eos
    - leaf
leaf2.eos:
  hostname: 172.100.1.14
  role: leaf
  data:
    name: leaf2
    loopback_ipv4: 1.1.1.4/32
    loopback_ipv6: 2001:1:1:1::4/128
    interfaces:
      eth1:
        name: Ethernet1
        desc: "To spine1"
        ipv4: 10.1.1.3/31
        ipv6: 2010:1:1:2::3/127
      eth2:
        name: Ethernet2
        desc: "To spine2"
        ipv4: 10.1.1.7/31
        ipv6: 2010:1:1:2::7/127
      eth3:
        name: Ethernet3
        desc: "To client2"
        ipv4: 10.1.1.9/31
        ipv6: 2010:1:1:2::9/127
  groups:
    - eos
    - leaf
...