---
spine1:
  hostname: 172.20.20.111
  data:
    role: spine
    asn: 65000
    router-id: 1.1.1.1
    neighbors:
      leaf1:
        lo0_v4: 1.1.1.3
        lo0_v6: 2001:1:1:1::3
        ipv4: 10.1.1.1
        ipv6: 2010:1:1:2::1
        remote-as: 65001
      leaf2:
        lo0_v4: 1.1.1.4
        lo0_v6: 2001:1:1:1::4
        ipv4: 10.1.1.3
        ipv6: 2010:1:1:2::3
        remote-as: 65002
    lo0:
      name: Loopback0
      desc: Loopback0
      ipv4: 1.1.1.300/32
      ipv6: 2001:1:1:1::1/128
    interfaces:
      eth1:
        name: Ethernet1
        role: fabric
        desc: "To leaf1"
        ipv4: 10.1.1.0/31
        ipv6: 2010:1:1:2::0/127
      eth2:
        name: Ethernet2
        role: fabric
        desc: "To leaf2"
        ipv4: 10.1.1.2/31
        ipv6: 2010:1:1:2::2/127
  groups:
    - eos
    - spine

spine2:
  hostname: 172.20.20.112
  data:
    role: spine
    asn: 65000
    router-id: 1.1.1.2
    neighbors:
      leaf1:
        lo0_v4: 1.1.1.3
        lo0_v6: 2001:1:1:1::3
        ipv4: 10.1.1.5
        ipv6: 2010:1:1:2::5
        remote-as: 65001
      leaf2:
        lo0_v4: 1.1.1.4
        lo0_v6: 2001:1:1:1::4
        ipv4: 10.1.1.7
        ipv6: 2010:1:1:2::7
        remote-as: 65002
    lo0:
      name: Loopback0
      desc: Loopback0
      ipv4: 1.1.1.2/32
      ipv6: 2001:1:1:1::2/128
    interfaces:
      eth1:
        name: Ethernet1
        role: fabric
        desc: "To leaf1"
        ipv4: 10.1.1.4/31
        ipv6: 2010:1:1:2::4/127
      eth2:
        name: Ethernet2
        role: fabric
        desc: "To leaf2"
        ipv4: 10.1.1.6/31
        ipv6: 2010:1:1:2::6/127
  groups:
    - eos
    - spine

leaf1:
  hostname: 172.20.20.121
  data:
    role: leaf
    asn: 65001
    router-id: 1.1.1.3
    neighbors:
      spine1:
        lo0_v4: 1.1.1.1
        lo0_v6: 2001:1:1:1::1
        ipv4: 10.1.1.0
        ipv6: 2010:1:1:2::0
        remote-as: 65000
      spine2:
        lo0_v4: 1.1.1.2
        lo0_v6: 2001:1:1:1::2
        ipv4: 10.1.1.4
        ipv6: 2010:1:1:2::4
        remote-as: 65000
    lo0:
      name: Loopback0
      desc: Loopback0
      ipv4: 1.1.1.3/32
      ipv6: 2001:1:1:1::3/128
    interfaces:
      eth1:
        name: Ethernet1
        role: fabric
        desc: "To spine1"
        ipv4: 10.1.1.1/31
        ipv6: 2010:1:1:2::1/127
      eth2:
        name: Ethernet2
        role: fabric
        desc: "To spine2"
        ipv4: 10.1.1.5/31
        ipv6: 2010:1:1:2::5/127
      eth3:
        name: Ethernet3
        role: client
        desc: "To client1"
        ipv4: 20.1.1.1/24
        ipv6: 20:1::1/64
  groups:
    - eos
    - leaf

leaf2:
  hostname: 172.20.20.122
  data:
    role: leaf
    asn: 65002
    router-id: 1.1.1.4
    neighbors:
      spine1:
        lo0_v4: 1.1.1.1
        lo0_v6: 2001:1:1:1::1
        ipv4: 10.1.1.2
        ipv6: 2010:1:1:2::2
        remote-as: 65000
      spine2:
        lo0_v4: 1.1.1.2
        lo0_v6: 2001:1:1:1::2
        ipv4: 10.1.1.6
        ipv6: 2010:1:1:2::6
        remote-as: 65000
    lo0:
      name: Loopback0
      desc: Loopback0
      ipv4: 1.1.1.4/32
      ipv6: 2001:1:1:1::4/128
    interfaces:
      eth1:
        name: Ethernet1
        role: fabric
        desc: "To spine1"
        ipv4: 10.1.1.3/31
        ipv6: 2010:1:1:2::3/127
      eth2:
        name: Ethernet2
        role: fabric
        desc: "To spine2"
        ipv4: 10.1.1.7/31
        ipv6: 2010:1:1:2::7/127
      eth3:
        name: Ethernet3
        role: client
        desc: "To client2"
        ipv4: 20.1.1.2/24
        ipv6: 20:1::2/64
  groups:
    - eos
    - leaf
...